name: hsp2_lti
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - attrs
  - backports
  - backports.functools_lru_cache
  - backports.shutil_get_terminal_size
  - backports.shutil_which
  - backports_abc
  - blas
  - bleach
  - ca-certificates
  - certifi
  - colorama
  - configparser
  - contextlib2
  - cycler
  - dateparser
  - decorator
  - defusedxml
  - docutils
  - entrypoints
  - enum34
  - freetype
  - funcsigs
  - functools32
  - futures
  - h5py
  - hdf5
  - icc_rt
  - icu
  - importlib_metadata
  - intel-openmp
  - ipaddress
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - libblas
  - libcblas
  - liblapack
  - libpng
  - libsodium
  - linecache2
  - llvmlite
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - more-itertools
  - msys2-conda-epoch
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numba
  - numexpr
  - numpy
  - openssl
  - pandas>=0.17.1
  - pandoc
  - pandocfilters
  - pathlib2
  - pickleshare
  - pip
  - prometheus_client
  - prompt_toolkit
  - pygments
  - pyparsing
  - pyqt
  - pyreadline
  - pyrsistent
  - python
  - python-dateutil>=2.1
  - pytz
  - pywin32
  - pywinpty
  - pyzmq
  - qgrid
  - qt
  - qtconsole
  - regex
  - scandir
  - scipy
  - send2trash
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - sqlite
  - tabulate
  - terminado
  - testpath
  - tornado
  - traceback2
  - traitlets
  - tzlocal
  - unittest2
  - vc
  - vs2008_runtime
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - win_unicode_console
  - wincertstore
  - winpty
  - zeromq
  - zipp
  - zlib
  - pip:
    - filelock
    - future
    - hspfbintoolbox
    - mando>=0.4
    - mock
    - pint
    - rst2ansi>=0.1.5
    - tables
    - tstoolbox
    - xlsxwriter

